API_HOST_URL: 'https://edxmoe.ilearnme.com'
ENVIRONMENT_DISPLAY_NAME: 'edxmoe.ilearnme.com'
PLATFORM_NAME: 'MOE'
PLATFORM_DESTINATION_NAME: 'edxmoe.ilearnme.com'
FEEDBACK_EMAIL_ADDRESS: 'info@raccoongang.com'
OAUTH_ENFORCE_SECURE: true
PUSH_NOTIFICATIONS: true
USER_PROFILES_ENABLED: true
DEBUG: true
OAUTH_CLIENT_ID: '0d7d01a1f2a866866285'
#ENABLE_MOBILE_REST_API: true
MY_VIDEOS_ENABLED: true
DISCUSSIONS_ENABLED: true
COURSE_VIDEOS_ENABLED: true
COURSE_ENROLLMENT : { TYPE : 'native', SEARCH_BAR_ENABLED : true }